"""initial BizPulse schema

Revision ID: 98ea2807c623
Revises: 
Create Date: 2026-09-30 02:57:03.262398
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '98ea2807c623'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('sub_industry', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('employee_range', sa.String(length=100), nullable=True),
    sa.Column('business_model', sa.String(length=100), nullable=True),
    sa.Column('main_products', sa.JSON(), nullable=False),
    sa.Column('main_markets', sa.JSON(), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('pulse_score', sa.Float(), nullable=True),
    sa.Column('opportunity_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_companies_opportunity_level'), 'companies', ['opportunity_level'], unique=False)
    op.create_index(op.f('ix_companies_province'), 'companies', ['province'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_index(op.f('ix_companies_sub_industry'), 'companies', ['sub_industry'], unique=False)
    op.create_table('llm_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_runs_input_hash'), 'llm_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_llm_runs_model'), 'llm_runs', ['model'], unique=False)
    op.create_index(op.f('ix_llm_runs_module'), 'llm_runs', ['module'], unique=False)
    op.create_index(op.f('ix_llm_runs_prompt_version'), 'llm_runs', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_llm_runs_status'), 'llm_runs', ['status'], unique=False)
    op.create_index(op.f('ix_llm_runs_target_id'), 'llm_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_llm_runs_target_type'), 'llm_runs', ['target_type'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('market_name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('current_solution', sa.Text(), nullable=True),
    sa.Column('current_cost', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('willingness_to_pay', sa.Integer(), nullable=True),
    sa.Column('automation_fit', sa.Integer(), nullable=True),
    sa.Column('competition', sa.Integer(), nullable=True),
    sa.Column('entry_difficulty', sa.Integer(), nullable=True),
    sa.Column('market_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('company_count', sa.Integer(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('high_value_company_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_market_name'), 'markets', ['market_name'], unique=True)
    op.create_index(op.f('ix_markets_market_score'), 'markets', ['market_score'], unique=False)
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=True)
    op.create_index(op.f('ix_markets_validation_status'), 'markets', ['validation_status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('reliability_grade', sa.String(length=1), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('collector_type', sa.String(length=100), nullable=True),
    sa.Column('collection_frequency', sa.String(length=100), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('collection_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_jobs_finished_at'), 'collection_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_name'), 'collection_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_collection_jobs_source_id'), 'collection_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_started_at'), 'collection_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('normalized_alias', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'normalized_alias', name='uq_company_alias')
    )
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_aliases_normalized_alias'), 'company_aliases', ['normalized_alias'], unique=False)
    op.create_table('company_markets',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('market_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'market_id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_id', sa.String(length=32), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('offer_name', sa.String(length=300), nullable=True),
    sa.Column('pricing_hypothesis', sa.String(length=300), nullable=True),
    sa.Column('target_company_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('conclusion', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_conclusion'), 'experiments', ['conclusion'], unique=False)
    op.create_index(op.f('ix_experiments_market_id'), 'experiments', ['market_id'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('pain_points',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('market_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_points_category'), 'pain_points', ['category'], unique=False)
    op.create_index(op.f('ix_pain_points_company_id'), 'pain_points', ['company_id'], unique=False)
    op.create_index(op.f('ix_pain_points_market_id'), 'pain_points', ['market_id'], unique=False)
    op.create_index(op.f('ix_pain_points_status'), 'pain_points', ['status'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_source_record_hash')
    )
    op.create_index(op.f('ix_source_records_collected_at'), 'source_records', ['collected_at'], unique=False)
    op.create_index(op.f('ix_source_records_company_id'), 'source_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_source_records_content_hash'), 'source_records', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_records_published_at'), 'source_records', ['published_at'], unique=False)
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_table('company_contacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('public_contact', sa.Text(), nullable=True),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('verified_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_contacts_company_id'), 'company_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_contacts_source_record_id'), 'company_contacts', ['source_record_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('market_id', sa.String(length=32), nullable=True),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('signal_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('heat_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fact_or_inference', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_collected_at'), 'signals', ['collected_at'], unique=False)
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_market_id'), 'signals', ['market_id'], unique=False)
    op.create_index(op.f('ix_signals_published_at'), 'signals', ['published_at'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_source_record_id'), 'signals', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('market_id', sa.String(length=32), nullable=True),
    sa.Column('primary_signal_id', sa.String(length=32), nullable=True),
    sa.Column('pain_point_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('purchase_intent', sa.String(length=50), nullable=True),
    sa.Column('estimated_budget_level', sa.String(length=50), nullable=True),
    sa.Column('budget_hypothesis_text', sa.Text(), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=False),
    sa.Column('budget_score', sa.Integer(), nullable=False),
    sa.Column('intent_score', sa.Integer(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('agent_fit_score', sa.Integer(), nullable=False),
    sa.Column('reachability_score', sa.Integer(), nullable=False),
    sa.Column('evidence_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pain_point_id'], ['pain_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_grade'), 'opportunities', ['grade'], unique=False)
    op.create_index(op.f('ix_opportunities_market_id'), 'opportunities', ['market_id'], unique=False)
    op.create_index(op.f('ix_opportunities_pain_point_id'), 'opportunities', ['pain_point_id'], unique=False)
    op.create_index(op.f('ix_opportunities_primary_signal_id'), 'opportunities', ['primary_signal_id'], unique=False)
    op.create_index(op.f('ix_opportunities_stage'), 'opportunities', ['stage'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_total_score'), 'opportunities', ['total_score'], unique=False)
    op.create_table('pain_point_evidences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pain_point_id', sa.String(length=32), nullable=False),
    sa.Column('signal_id', sa.String(length=32), nullable=True),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pain_point_id'], ['pain_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_point_evidences_pain_point_id'), 'pain_point_evidences', ['pain_point_id'], unique=False)
    op.create_index(op.f('ix_pain_point_evidences_signal_id'), 'pain_point_evidences', ['signal_id'], unique=False)
    op.create_index(op.f('ix_pain_point_evidences_source_record_id'), 'pain_point_evidences', ['source_record_id'], unique=False)
    op.create_table('experiment_opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'opportunity_id', name='uq_experiment_opportunity')
    )
    op.create_index(op.f('ix_experiment_opportunities_experiment_id'), 'experiment_opportunities', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_opportunities_opportunity_id'), 'experiment_opportunities', ['opportunity_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('experiment_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_title', sa.String(length=200), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('meeting', sa.Boolean(), nullable=False),
    sa.Column('quote_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('deal', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reject_reason', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_company_id'), 'interactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_interactions_contact_at'), 'interactions', ['contact_at'], unique=False)
    op.create_index(op.f('ix_interactions_experiment_id'), 'interactions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_interactions_opportunity_id'), 'interactions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_interactions_reject_reason'), 'interactions', ['reject_reason'], unique=False)
    op.create_index(op.f('ix_interactions_response_type'), 'interactions', ['response_type'], unique=False)
    op.create_table('opportunity_evidences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('signal_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_evidences_opportunity_id'), 'opportunity_evidences', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_evidences_signal_id'), 'opportunity_evidences', ['signal_id'], unique=False)
    op.create_index(op.f('ix_opportunity_evidences_source_record_id'), 'opportunity_evidences', ['source_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_evidences_source_record_id'), table_name='opportunity_evidences')
    op.drop_index(op.f('ix_opportunity_evidences_signal_id'), table_name='opportunity_evidences')
    op.drop_index(op.f('ix_opportunity_evidences_opportunity_id'), table_name='opportunity_evidences')
    op.drop_table('opportunity_evidences')
    op.drop_index(op.f('ix_interactions_response_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_reject_reason'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_opportunity_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_experiment_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_contact_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_company_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_experiment_opportunities_opportunity_id'), table_name='experiment_opportunities')
    op.drop_index(op.f('ix_experiment_opportunities_experiment_id'), table_name='experiment_opportunities')
    op.drop_table('experiment_opportunities')
    op.drop_index(op.f('ix_pain_point_evidences_source_record_id'), table_name='pain_point_evidences')
    op.drop_index(op.f('ix_pain_point_evidences_signal_id'), table_name='pain_point_evidences')
    op.drop_index(op.f('ix_pain_point_evidences_pain_point_id'), table_name='pain_point_evidences')
    op.drop_table('pain_point_evidences')
    op.drop_index(op.f('ix_opportunities_total_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_primary_signal_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_pain_point_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_market_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_grade'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_record_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_published_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_market_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_collected_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_company_contacts_source_record_id'), table_name='company_contacts')
    op.drop_index(op.f('ix_company_contacts_company_id'), table_name='company_contacts')
    op.drop_table('company_contacts')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_published_at'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_content_hash'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_company_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_collected_at'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_pain_points_status'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_market_id'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_company_id'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_category'), table_name='pain_points')
    op.drop_table('pain_points')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_market_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_conclusion'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('company_markets')
    op.drop_index(op.f('ix_company_aliases_normalized_alias'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_started_at'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_source_id'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_name'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_finished_at'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_markets_validation_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_market_score'), table_name='markets')
    op.drop_index(op.f('ix_markets_market_name'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_llm_runs_target_type'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_target_id'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_status'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_prompt_version'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_module'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_model'), table_name='llm_runs')
    op.drop_index(op.f('ix_llm_runs_input_hash'), table_name='llm_runs')
    op.drop_table('llm_runs')
    op.drop_index(op.f('ix_companies_sub_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_province'), table_name='companies')
    op.drop_index(op.f('ix_companies_opportunity_level'), table_name='companies')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
