"""t04 signal candidates evidences and lifecycle

Revision ID: a0ae25d999ed
Revises: 0cad4bcaffa3
Create Date: 2026-09-30 18:28:56.012191
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a0ae25d999ed'
down_revision: Union[str, None] = '0cad4bcaffa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_type', sa.String(length=80), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('rule_confidence', sa.Integer(), nullable=False),
    sa.Column('llm_confidence', sa.Integer(), nullable=True),
    sa.Column('final_confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='REVIEW', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('structured_json', sa.JSON(), nullable=False),
    sa.Column('fact_summary', sa.Text(), nullable=True),
    sa.Column('inference_summary', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_candidates_candidate_type'), 'signal_candidates', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_signal_candidates_company_id'), 'signal_candidates', ['company_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_final_confidence'), 'signal_candidates', ['final_confidence'], unique=False)
    op.create_index(op.f('ix_signal_candidates_fingerprint'), 'signal_candidates', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_signal_candidates_signal_id'), 'signal_candidates', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_source_record_id'), 'signal_candidates', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_status'), 'signal_candidates', ['status'], unique=False)
    op.create_table('signal_evidences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('signal_id', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_evidences_signal_id'), 'signal_evidences', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_evidences_source_record_id'), 'signal_evidences', ['source_record_id'], unique=False)
    op.add_column('signals', sa.Column('fact_summary', sa.Text(), nullable=True))
    op.add_column('signals', sa.Column('inference_summary', sa.Text(), nullable=True))
    op.add_column('signals', sa.Column('signal_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('signals', sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signals', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signals', sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signals', sa.Column('created_by', sa.String(length=20), nullable=False))
    op.add_column('signals', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('signals', sa.Column('change_type', sa.String(length=30), nullable=True))
    op.add_column('signals', sa.Column('change_value', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_signals_confidence'), 'signals', ['confidence'], unique=False)
    op.create_index(op.f('ix_signals_first_seen_at'), 'signals', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_signals_signal_fingerprint'), 'signals', ['signal_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_source_records_url'), 'source_records', ['url'], unique=False)
    op.drop_index(op.f('ix_signals_signal_fingerprint'), table_name='signals')
    op.drop_index(op.f('ix_signals_first_seen_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_confidence'), table_name='signals')
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.drop_column('signals', 'change_value')
    op.drop_column('signals', 'change_type')
    op.drop_column('signals', 'prompt_version')
    op.drop_column('signals', 'created_by')
    op.drop_column('signals', 'stale_at')
    op.drop_column('signals', 'last_seen_at')
    op.drop_column('signals', 'first_seen_at')
    op.drop_column('signals', 'signal_fingerprint')
    op.drop_column('signals', 'inference_summary')
    op.drop_column('signals', 'fact_summary')
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    op.create_index(op.f('ix_collection_jobs_finished_at'), 'collection_jobs', ['finished_at'], unique=False)
    op.drop_index(op.f('ix_signal_evidences_source_record_id'), table_name='signal_evidences')
    op.drop_index(op.f('ix_signal_evidences_signal_id'), table_name='signal_evidences')
    op.drop_table('signal_evidences')
    op.drop_index(op.f('ix_signal_candidates_status'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_source_record_id'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_signal_id'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_fingerprint'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_final_confidence'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_company_id'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_candidate_type'), table_name='signal_candidates')
    op.drop_table('signal_candidates')
    # ### end Alembic commands ###
